### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by kmusialik** [ak-ambi/python-airly#5]
when i run sample_measurements.py i get:

  File "/Users/krzysztofmusialik/Desktop/ready_projects/airly/python-airly-master/samples/sample_measurements.py", line 56, in <module>
    loop.run_until_complete(main())

  File "/anaconda3/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()

  File "/anaconda3/lib/python3.7/asyncio/base_events.py", line 526, in run_forever
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running

Measurements for specific installation:

Any idea how to solve this issue?

**Comment by ak-ambi** [comment]
Hi @kmusialik,

I could not reproduce this behavior. It seems that asyncio loop is started more than once, but I don't understand what started the loop for the first time. 

This `loop.run_until_complete(main())` from `sample_measurements.py`, line 56 should one of the first lines executed, so the loop should not be running at this point.

Please let me know how you execute the command (try to reproduce), and what version of python, asyncio and aiohttp do you have?

**Comment by ak-ambi** [comment]
@kmusialik I found the problem. It is the bug in ipython/spyder: https://github.com/spyder-ide/spyder/issues/7096. Just switch to the newest version as this is reported to be fixed.
